name: 'latex-env'
description: 'latex-env'
inputs:
  message:
    description: 'my message'
    required: true
    default: 'hello'
  source:
    description: 'source script'
    required: true
    default: ''
  entryPoint:
    description: 'entryPoint'
    required: true
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.message }}