name: 'latex-env'
description: 'latex-env'
inputs:
  message:
    description: 'my message'
    required: true
    default: 'hello'
  source:
    description: 'source script'
    required: true
    default: ''
  enter:
    description: 'enter'
    required: true
    default: 'echo "hello from echo"'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.message }}
    - ${{ inputs.enter }}